import math as m

print(m.sqrt(25))
print(m.floor(2.9))
print(m.ceil(2.9))
print(m.pi)
print(m.e)
print(m.sin(m.radians(90)))
print(m.cos(m.radians(90)))
print(m.tan(m.radians(90)))
print(m.log(10, m.e))
print(m.log10(10))
print(m.log2(10))
print(m.pow(2, 3))
print(m.factorial(5))
print(m.gcd(2, 4))
print(m.degrees(90))
print(m.radians(90))
print(m.inf)
print(m.nan)
print(m.floor(2.9))
print(m.fabs(-2.9))
print(m.fmod(2, 3))  # remainder
print(m.copysign(2, -3))
print(m.isfinite(2))
print(m.isinf(2))
print(m.isnan(2))
print(m.modf(2.9))
print(m.frexp(2.9))
print(m.ldexp(2.9, 2))
print(m.exp(2.9))
print(m.expm1(2.9))
print(m.hypot(2, 3))
print(m.acos(0.5))
print(m.asin(0.5))
